#!/usr/bin/env bash
set -euo pipefail

# Ghostty + Starship + Catppuccin Mocha 一键配置脚本
# 目标平台：macOS + zsh
# 用法：bash setup-ghostty-catppuccin.sh
# 预览：bash setup-ghostty-catppuccin.sh --dry-run

DRY_RUN=0
OPEN_GHOSTTY=1
TS="$(date +%Y%m%d-%H%M%S)"

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --no-open) OPEN_GHOSTTY=0 ;;
    -h|--help)
      cat <<'HELP'
Usage: bash setup-ghostty-catppuccin.sh [--dry-run] [--no-open]

Options:
  --dry-run   只打印将要执行的动作，不修改系统
  --no-open   配置完成后不自动打开 Ghostty
HELP
      exit 0
      ;;
    *) echo "Unknown option: $arg" >&2; exit 1 ;;
  esac
done

log()  { printf '\033[1;32m[INFO]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[WARN]\033[0m %s\n' "$*"; }
err()  { printf '\033[1;31m[ERR ]\033[0m %s\n' "$*" >&2; }

run() {
  if [[ "$DRY_RUN" == "1" ]]; then
    printf '+ %q ' "$@"; printf '\n'
  else
    "$@"
  fi
}

write_file() {
  local file="$1"
  local content="$2"
  if [[ "$DRY_RUN" == "1" ]]; then
    log "Would write: $file"
  else
    printf '%s' "$content" > "$file"
  fi
}

backup_file() {
  local file="$1"
  if [[ -f "$file" ]]; then
    local backup="${file}.bak.${TS}"
    log "Backup $file -> $backup"
    run cp "$file" "$backup"
  fi
}

ensure_writable_file() {
  local file="$1"
  if [[ -e "$file" && ! -w "$file" ]]; then
    warn "$file 当前不可写，尝试修复 owner 和写权限"
    run sudo chown "$USER":staff "$file"
    run chmod u+rw "$file"
  fi
}

brew_install() {
  local pkg="$1"
  if brew list "$pkg" >/dev/null 2>&1; then
    log "Homebrew formula already installed: $pkg"
  else
    log "Install Homebrew formula: $pkg"
    run brew install "$pkg"
  fi
}

brew_cask_install() {
  local cask="$1"
  if brew list --cask "$cask" >/dev/null 2>&1; then
    log "Homebrew cask already installed: $cask"
  else
    log "Install Homebrew cask: $cask"
    run brew install --cask "$cask"
  fi
}

if [[ "$(uname -s)" != "Darwin" ]]; then
  err "当前脚本面向 macOS。Linux/WSL 可参考 README 单独适配。"
  exit 1
fi

log "Start Ghostty + Starship + Catppuccin Mocha setup"

# 1. 安装 Homebrew
if ! command -v brew >/dev/null 2>&1; then
  warn "Homebrew not found, installing Homebrew..."
  if [[ "$DRY_RUN" == "1" ]]; then
    echo '+ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  else
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
fi

# 让当前 shell 立刻识别 brew
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

if ! command -v brew >/dev/null 2>&1; then
  err "Homebrew 安装后仍不可用，请检查 PATH。"
  exit 1
fi

log "Update Homebrew metadata"
run brew update

# 2. 安装 Ghostty、字体、Starship 和常用 CLI
brew_cask_install ghostty
brew_cask_install font-meslo-lg-nerd-font

for pkg in \
  starship \
  zsh-autosuggestions \
  zsh-syntax-highlighting \
  zsh-completions \
  eza \
  bat \
  fd \
  ripgrep \
  fzf \
  btop \
  zoxide \
  jq \
  tldr \
  git-delta \
  lazygit \
  fnm
  do
    brew_install "$pkg"
  done

# 3. 写入 Ghostty 配置
GHOSTTY_DIR="$HOME/.config/ghostty"
GHOSTTY_CONFIG="$GHOSTTY_DIR/config.ghostty"
run mkdir -p "$GHOSTTY_DIR"
backup_file "$GHOSTTY_CONFIG"

GHOSTTY_CONTENT=$(cat <<'GHOSTTY_EOF'
# Generated by setup-ghostty-catppuccin.sh
# Theme
theme = Catppuccin Mocha

# Font
font-family = MesloLGS NF
font-size = 15

# Window
window-padding-x = 12
window-padding-y = 10
background-opacity = 0.94
background-blur = true
macos-titlebar-style = transparent

# Cursor
cursor-style = block
cursor-style-blink = false

# Interaction
copy-on-select = clipboard
mouse-hide-while-typing = true
confirm-close-surface = false

# Shell integration
shell-integration = zsh
GHOSTTY_EOF
)
write_file "$GHOSTTY_CONFIG" "$GHOSTTY_CONTENT"

# 兼容旧路径：如果用户曾用过 macOS Application Support 路径，则给出提示但不覆盖
OLD_GHOSTTY_DIR="$HOME/Library/Application Support/com.mitchellh.ghostty"
if [[ -d "$OLD_GHOSTTY_DIR" ]]; then
  warn "检测到旧配置目录：$OLD_GHOSTTY_DIR"
  warn "本脚本使用 XDG 路径：$GHOSTTY_CONFIG"
fi

# 4. 写入 Starship Catppuccin Mocha 配置
STARSHIP_CONFIG="$HOME/.config/starship.toml"
run mkdir -p "$HOME/.config"
backup_file "$STARSHIP_CONFIG"

STARSHIP_CONTENT=$(cat <<'STARSHIP_EOF'
"$schema" = 'https://starship.rs/config-schema.json'

palette = 'catppuccin_mocha'
add_newline = true
command_timeout = 800
scan_timeout = 30

format = """
[](red)\
$os\
$username\
[](bg:peach fg:red)\
$directory\
[](bg:yellow fg:peach)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:sapphire)\
$conda\
[](fg:sapphire bg:lavender)\
$time\
[ ](fg:lavender)\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user]($style)'

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:crust bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:crust bg:yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "fg:crust bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
STARSHIP_EOF
)
write_file "$STARSHIP_CONFIG" "$STARSHIP_CONTENT"

# 5. 写入 zsh 配置块
ZSHRC="$HOME/.zshrc"
touch "$ZSHRC"
ensure_writable_file "$ZSHRC"
backup_file "$ZSHRC"

ZSH_BLOCK=$(cat <<'ZSH_EOF'
# >>> ghostty-starship-catppuccin setup >>>

# Homebrew environment
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

# Zsh plugins installed by Homebrew
if [[ -f "$(brew --prefix 2>/dev/null)/share/zsh-autosuggestions/zsh-autosuggestions.zsh" ]]; then
  source "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi

if [[ -f "$(brew --prefix 2>/dev/null)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]]; then
  source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

if [[ -d "$(brew --prefix 2>/dev/null)/share/zsh-completions" ]]; then
  fpath=("$(brew --prefix)/share/zsh-completions" $fpath)
  autoload -Uz compinit
  compinit
fi

# fzf key bindings and completion
if command -v fzf >/dev/null 2>&1; then
  source <(fzf --zsh) 2>/dev/null || true
fi

# zoxide smart cd
if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

# fnm Node.js manager
if command -v fnm >/dev/null 2>&1; then
  eval "$(fnm env --use-on-cd --shell zsh)"
fi

# Useful aliases
if command -v eza >/dev/null 2>&1; then
  alias ls='eza --icons --group-directories-first'
  alias ll='eza -la --icons --group-directories-first'
  alias lt='eza --tree --icons --level=2'
fi

if command -v bat >/dev/null 2>&1; then
  alias cat='bat'
fi

if command -v fd >/dev/null 2>&1; then
  alias find='fd'
fi

if command -v rg >/dev/null 2>&1; then
  alias grep='rg'
fi

if command -v btop >/dev/null 2>&1; then
  alias top='btop'
fi

if command -v lazygit >/dev/null 2>&1; then
  alias lg='lazygit'
fi

# Starship prompt, keep it near the end of ~/.zshrc
eval "$(starship init zsh)"

# <<< ghostty-starship-catppuccin setup <<<
ZSH_EOF
)

if [[ "$DRY_RUN" == "1" ]]; then
  log "Would replace managed block in $ZSHRC"
else
  python3 - "$ZSHRC" "$ZSH_BLOCK" <<'PY'
import re
import sys
from pathlib import Path

path = Path(sys.argv[1])
block = sys.argv[2]
text = path.read_text() if path.exists() else ""
pattern = r"\n?# >>> ghostty-starship-catppuccin setup >>>.*?# <<< ghostty-starship-catppuccin setup <<<\n?"
text = re.sub(pattern, "\n", text, flags=re.S).rstrip() + "\n\n" + block + "\n"
path.write_text(text)
PY
fi

# 6. 安装 Node LTS，可失败但不终止整个脚本
if command -v fnm >/dev/null 2>&1; then
  log "Install Node.js LTS via fnm"
  if [[ "$DRY_RUN" == "1" ]]; then
    echo '+ fnm install --lts && fnm default lts-latest'
  else
    eval "$(fnm env --use-on-cd --shell bash)"
    fnm install --lts || warn "fnm install --lts failed, you can run it manually later."
    fnm default lts-latest || true
  fi
fi

log "Verification commands"
echo "  ghostty +list-themes | grep -i Catppuccin"
echo "  ghostty +list-fonts  | grep -i Meslo"
echo "  starship explain"
echo "  source ~/.zshrc"

if [[ "$OPEN_GHOSTTY" == "1" && "$DRY_RUN" != "1" ]]; then
  open -a Ghostty || true
fi

log "Done. If Ghostty theme/font is not refreshed, restart Ghostty."
